name: WOOP-MAIN

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    strategy:
      matrix:
        node-version: [ 18.16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: eeafbac02f93c14b9f38c8da0c7577ef
          projectName: portfolio-fe
          directory: /
