name: WOOP-MAIN

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Deploy

    strategy:
      matrix:
        node-version: [ 18.16 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: Project-Woop/portfolio-fe@master
        with:
            branch: gh-pages
            folder: dist/portfolio-fe
